src/ship_receiver_plugin.cpp
=> Correct processing of pushtx actions in ship_receiver_plugin

README.md
=> Add conan install to build instructions

peripherals/proxy/eth-jsonrpc-access.lua
=> [0.6] Support batch requests in tx_proxy

peripherals/proxy/eth-jsonrpc-access.lua
Currently include fix for #89 
May add more later.
=> [0.6->main]  Support batch requests in tx_proxy

CMakeLists.txt
Resolve #95 
Resolve #83 
Should also include test fixes in silkworm but it has noting to do with this repo.
=> [0.6->main] Update silkworm to include 0.6.1 fixes

tests/nodeos_eos_evm_ws_test_basic.py
=> integration test of web socket handler

src/rpc_plugin.cpp
Resolve #88 and #113 and #106
silkworm updated to track head of master
=> [0.6->main] Merge in release 0.6 fix: trace quirk mode, eth_call blockhash fix, and eth_estimateGas now accept extra parameter

.github/workflows/node.yml, tests/CMakeLists.txt, tests/nodeos_eos_evm_ws_test_fork.py
Resolves #76 This will test the fork handling logic in web socket server
=> Websocket integration test for fork handling 

.github/workflows/node.yml
=> [0.6] Update submodule to contain the fix.

.github/workflows/node.yml, CMakeLists.txt
=> [0.6 ->main] Merge in the fix for the quirk mode. Also include some fix to CI

tests/nodeos_eos_evm_test.py
=> Add special signatures handling integration tests

peripherals/eos-evm-ws-proxy/block-monitor.js
=> Extra checks for block hash when batch requesting block and logs.

peripherals/proxy/nginx.conf
=> [0.6] Enable long connection from tx_proxy to miner

peripherals/proxy/nginx.conf
=> [0.6->0.7] Merge nginx config change for long connection

peripherals/proxy/Dockerfile
=> [0.7->main] Merge in nginx docker file fix for WS_ENDPOINT

src/ship_receiver_plugin.cpp
=> [0.6->0.7] pull option changes to disable ship-start-from options

peripherals/eos-evm-ws-proxy/README.md
Resolves #142  for release/0.7
=> [0.7] Update README.md

CMakeLists.txt, cmake/conan.cmake, cmake/profiles/linux_arm_gcc_11_debug, cmake/profiles/linux_arm_gcc_11_release
Resolve #52 
Note this PR needs to be updated to refer to the silkworm after the merge of related fixes.
=> Support arm

src/engine_plugin.cpp, src/rpc_plugin.cpp
=> remove etherbase setting

src/rpc_plugin.cpp
=> remove engin-port config

README.md, src/block_conversion_plugin.cpp
=> [release/0.7] Kayan fix timestamp to blocknum

README.md, src/block_conversion_plugin.cpp
=> [0.7 -> main] fix timestamp to blocknum for main 

tests/nodeos_eos_evm_test.py
=> gas parameter integration test

src/engine_plugin.cpp, src/rpc_plugin.cpp
Resolve #203 
Resolve #204 
Details discussed in #189
=> Fix mdbx related issues

tests/nodeos_eos_evm_test.py
=> [1.0 -> main] add get transaction & get transaction receipt from rpc test

tests/nodeos_eos_evm_ws_test_basic.py, tests/nodeos_eos_evm_ws_test_fork.py
https://github.com/eosnetworkfoundation/eos-evm-node/issues/243
=> [1.0] fix estimate gas

tests/nodeos_eos_evm_different_token_test.py, tests/nodeos_eos_evm_gasparam_fork_test.py, tests/nodeos_eos_evm_test.py
=> [1.0] Update silkworm 1.0.2

tests/nodeos_eos_evm_ws_test_basic.py, tests/nodeos_eos_evm_ws_test_fork.py
=> [1.0 -> main] fix estimate gas

tests/nodeos_eos_evm_different_token_test.py, tests/nodeos_eos_evm_gasparam_fork_test.py, tests/nodeos_eos_evm_test.py, tests/nodeos_eos_evm_ws_test_basic.py, tests/nodeos_eos_evm_ws_test_fork.py
=> [1.0 -> main] Update silkworm 1.0.2

src/rpc_plugin.cpp, tests/nodeos_eos_evm_different_token_test.py
Resovles https://github.com/eosnetworkfoundation/eos-evm-node/issues/251 , use a completely different chain id in nodeos_eos_evm_different_token_test.py
(From @taokayan dynamic chainid #252)
=> [1.0] dynamic chainid

.cicd/defaults.json, .github/workflows/node.yml, tests/nodeos_eos_evm_test.py
=> [1.0] Update CICD to use Spring

CMakeLists.txt
=> [0.7] bump version to 0.7.1

tests/nodeos_eos_evm_test.py
=> [1.0] Fix eth_call when evm_version>0

tests/nodeos_eos_evm_test.py
=> [1.0 -> main] Fix eth_call when evm_version>0

CMakeLists.txt
=> [1.0.1] Bump 1.0.1 version

src/ship_receiver_plugin.cpp
=> evmtx order

src/ship_receiver_plugin.cpp
=> [1.0 -> main] forword evmtx ordering fix to main

peripherals/proxy/nginx.conf
Resolve #307 
Already manually changed the scripts in testnet and mainnet.
=> Block buggy debug calls in nginx

CMakeLists.txt, peripherals/proxy/eth-jsonrpc-access.lua
=> [1.0->main] Pull fixes to enable eth_gasPrice

src/block_conversion_plugin.cpp
=> fix gas v3

src/blockchain_plugin.cpp, src/channels.hpp, src/engine_plugin.cpp
=> [1.0] Exit instead of silently continue for exceptions when processing blocks

src/blockchain_plugin.cpp, src/channels.hpp, src/engine_plugin.cpp
=> [2.0->main] Exit instead of silently continue for exceptions when processing blocks 

tests/nodeos_eos_evm_different_token_test.py, tests/nodeos_eos_evm_gasparam_fork_test.py
=> [1.0-> 2.0] Fix unstable integration tests & use savanna finality (gas param fork test, different gas token test)

tests/nodeos_eos_evm_different_token_test.py, tests/nodeos_eos_evm_gasparam_fork_test.py
=> [1.0->main] forward integration test fixes to main

.gitmodules
Update remote url.
Update silkworm to correct commit.
No functionality changes expected.
=> [2.0] Update silkworm

tests/nodeos_evm_server.py, tests/nodeos_evm_ws_test_basic.py, tests/nodeos_evm_ws_test_fork.py
Resolve #384  update test case to use instant finality
=> [1.0->2.0] Ensure integration tests all use Savanna consensus
