VaultaFoundation/evm-node

- src/rpc_plugin.cpp
> Use regular endpoints as the default values in command line options

- peripherals/eos-evm-ws-proxy/block-monitor.js
- peripherals/eos-evm-ws-proxy/config.js
- peripherals/eos-evm-ws-proxy/subscription-server.js
- peripherals/eos-evm-ws-proxy/websocket-handler.js
Resolves #91 
add web3_rpc_test_endpoint in config
add miner_rpc_endpoint in config
add whitelist_methods in config
always group all requests in a batch to send to either rpc endpoint or rpc test endpoint.
reduce frequency of get eos lib
add minmum (180) size in this.reversible_blocks as protection in case of evm-rpc is out of sync with leap endpoint
> route websocket proxy traffics to different destinations

- peripherals/proxy/nginx.conf
Solve #85 
Currently the limit is set to 5r/s burst 25 with dry run mode. 
We should run with dry run after upgraded to 0.7 and try to figure out a proper limit before we really apply the limit.
> Prepare rate limit in nginx config files

- peripherals/proxy/Dockerfile
Please make sure it works before merge.
> [0.7] Fix docker file to take WS_ENDPOINT

- src/block_conversion_plugin.cpp
- src/engine_plugin.cpp
- src/engine_plugin.hpp
- src/ship_receiver_plugin.cpp
- src/ship_receiver_plugin.hpp
Remove support for start from certain eos id functionality.
Resolve #151
> Support sync start from certain evm height

- src/ship_receiver_plugin.cpp
Resolve #151 
Those options have already been removed by #170 in main. So we pull this fix by doing nothing.
Also, removed some unused error handling code regarding those options as boost will throw before code reach there if we removed the options.
> [0.7->main] Disable deprecated ship-start-from options

- .cicd/defaults.json
- .github/workflows/node.yml
- tests/nodeos_eos_evm_server.py
- tests/nodeos_eos_evm_test.py
- tests/nodeos_eos_evm_ws_test_basic.py
- tests/nodeos_eos_evm_ws_test_fork.py
> Try update cicd to use leap 5

- .cicd/defaults.json
- .github/workflows/node.yml
- tests/nodeos_eos_evm_server.py
- tests/nodeos_eos_evm_test.py
- tests/nodeos_eos_evm_ws_test_basic.py
- tests/nodeos_eos_evm_ws_test_fork.py
> [0.7] make release/0.7 test cases with leap 5

- src/block_conversion_plugin.cpp
- src/block_conversion_plugin.hpp
- src/blockchain_plugin.cpp
- src/channels.hpp
- src/ship_receiver_plugin.cpp
- src/utils.hpp
Resolve #186 
The planned implementation is like this:
1 ship_receiver_plugin will check if it received a configchange event, if found, make sure it's the first related action in a block, save the new config in the resulting native_block/
2 block_conversion_plugin will make sure if there's a new config in the incoming native_block, it should be the first one native block for a resulting evm block. Then: 
a save the new config in the resulting evm block
b change the evm block's consensus_parameter_index to it's own height.
3 blockchain_plugin will detect if there's new config coming in with the evm blocks. if so:
a save new parameters
b verify_chain for the blocks before if necessary
c insert the incoming blcok
d verify chain (may be not necessary)
-- EDIT: after some double thinking, we …
> Process configchange event and save the parameters in some data structure.

- src/blockchain_plugin.cpp
Resolve #196 
Need updating submodule after silkworm merge.
> Fix runtime state related function

- src/engine_plugin.cpp
> Fix issues when LIB recorded from previous shutdown is at the edge of a gap

- tests/nodeos_eos_evm_test.py
> [1.0] add estimate_gas test

- src/engine_plugin.cpp
- src/rpc_plugin.cpp
- tests/nodeos_eos_evm_ws_test_basic.py
- tests/nodeos_eos_evm_ws_test_fork.py
> [0.7] Kayan port mdbx fix

- .cicd/defaults.json
- .github/workflows/node.yml
- tests/nodeos_eos_evm_test.py
Resolves https://github.com/eosnetworkfoundation/eos-evm-node/issues/224
> [1.0 -> main] Update CICD to use Spring

- tests/nodeos_eos_evm_gasparam_fork_test.py
- tests/nodeos_eos_evm_test.py
> savanna transition integration test for EVM

- tests/nodeos_eos_evm_gasparam_fork_test.py
- tests/nodeos_eos_evm_test.py
> [1.0->main] Kayan 1.0 to main test savanna

- LICENSE
Forwards PRs #296 and #297 to `main` branch.
However, the `silkworm` submodule is updated to use the head of the `master` branch which also now includes the license changes.
> [1.0.2 -> main] Change to BSL licensing scheme 

- .cicd/defaults.json
For EOS EVM Node v1.x integration tests, we should use the latest stable versions of Spring (1.x) and CDT (4.x) rather than the versions in the respective repo's `main` branch. Also, the latest stable 1.x version of EOS EVM Miner should be used.
> [1.0.2] Update versions/branches to use for CI dependencies

- .cicd/defaults.json
Forwards #299 to `main` branch.
This means we continue using the latest stable versions of Spring (1.x) and CDT (4.x) rather than the versions in the respective repo's `main` branch. Unless we have a good reason to use the latest head of Spring development for our EOS EVM Node integration tests, it is a better idea to stick with a stable version.
However, we do want to use the `main` branch for the EOS EVM Contract and EOS EVM Miner dependencies.
> [1.0.2 -> main] Update versions/branches to use for CI dependencies

- peripherals/proxy/eth-jsonrpc-access.lua
Resolve #339 
1 We open the API in silkworm
2 We make sure the batches containing 'eth_gasPrice' is properly forwarded.
> [1.0] Allow batch eth_gasPrice

- src/block_conversion_plugin.cpp
For #344 
The problem only happens when the second EOS block of an EVM block is forked. 
The current test framework seems to have some difficulty to accurately emulate this case.
Maybe we should fix the issue first and slit the unit test to a separate issue so that we can have it fixed asap?
> [1.0] Encode transaction properly in the tx removal step during fork

- CMakeLists.txt
- src/block_conversion_plugin.cpp
> [1.0->main] Encode transaction properly in the tx removal step during fork

- tests/nodeos_eos_evm_gasparam_fork_test.py
> fix gas param fork test
